# You can use %PLAYER% for player name or %RANK% for rank name
# An example can be seen below
prevail:
  name: '&4&lPrevail' # Set to anything, doesn't really matter since its not used
  rankname: 'Prevail' # Set this to whatever the pex rank name is
  commands:
    - 'bc -raw &c&l%PLAYER% &e&lhas reclaimed their &4&lPrevail Rank &e&lfrom the store! &b&lhttp://buy.prevailpots.com/'
    - 'stafflives give %PLAYER% 40'
    - 'crate givekey %PLAYER% Vague 40'
    - 'crate givekey %PLAYER% Mystical 25'
    - 'crate givekey %PLAYER% Cryptic 15'